resources:         
  containers:
  - container: 
    connection: 
    image: ubuntu:18.04

trigger:
- master

variables:
  dockerId: 
  username: 
  imageName: 
  pswd: 
  DockerContainerRegistry: ''

# Starter pipeline
steps:

- task: Docker@2
  displayName: 'building and pushing the docker container hello-world'
    # Do NOT push this files because it shall be build with docker buildx for multiarch.
  inputs:
    containerRegistry: $(DockerContainerRegistry)
    repository: helloworldpoc
    tags: |
      x64-latest
      latest
      $(Build.BuildID)
    command: buildAndPush
    buildContext: './'
    Dockerfile: './Dockerfile'  
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-service-catalog'
    regionName: 'eu-central-1'
    scriptType: 'inline'
    inlineScript: |
      aws s3 sync src/products/ s3://terraform-config-255639296009/

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-service-catalog'
    regionName: 'eu-central-1'
    stackName: 'service-catalog-poc'
    templateSource: 'file'
    templateFile: 'src/cf-service-catalog.yaml'
    logRequest: true
    logResponse: true

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'
