resources:         
  containers:
  - container: dielaisConnection
    connection: dielaisConnection
    image: ubuntu:18.04

trigger:
- master

variables:
  dockerId: 
  username: mazembo
  imageName: 
  pswd: Nditukulu79
  DockerContainerRegistry: 'dielaisConnection'

# Starter pipeline
steps:

- task: Docker@2
  displayName: 'building and pushing the docker container hello-world'
    # Do NOT push this files because it shall be build with docker buildx for multiarch.
  inputs:
    containerRegistry: $(DockerContainerRegistry)
    repository: helloworldpoc
    tags: |
      x64-latest
      latest
      $(Build.BuildID)
    command: buildAndPush
    buildContext: './'
    Dockerfile: './Dockerfile'  
