version: '3'

services:
    nginx-helloworld:
      image: nginx:latest
      container_name: nginx-helloworld
      ports:
        - "80:80"
      volumes:
        - "./index.html:/helloworld-storage"
        - "./nginx.conf:/etc/nginx/nginx.conf"
      environment:
        - NGINX_PORT=80
      command: /bin/bash -c "exec nginx -g 'daemon off;'"
volumes:
  helloworld-storage: